CREATE USER admin WITH LOGIN SUPERUSER PASSWORD '1234';

CREATE USER gestor;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA peliculas TO gestor;

CREATE USER critico;
GRANT SELECT ON ALL TABLES IN SCHEMA peliculas TO critico;
GRANT INSERT ON peliculas.criticas TO critico;

CREATE USER cliente;
GRANT SELECT ON ALL TABLES IN SCHEMA peliculas TO cliente;